import type { Metadata } from "next";
import MainLayout from "@/components/layout/main-layout";

export const metadata: Metadata = {
  title: "Next retail",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MainLayout>
      {children}
    </MainLayout>
  );
}
